### ISSUE TITLE
Docs: outsideGrails.adoc

### ISSUE THREAD

**Issue by ysb33r** [grails/gorm-hibernate5#5]
A bit of context. _I'm trying to put a basic sample project together (which probably will lead to a blog) about a standalone GORM & Hibernate 5. The approach to it is from the viewpoint of someone who knows nothing about Grails or Spring, but has heard good stuff abotu GORM and what to try it out_.

Based upon that I have crafted up https://github.com/ysb33r/SampleProjects/tree/GormStandalone/BasicHibernate trying to rely only on the current docs. This sample project fails because the schema is never created. Effectively there are bits of information missing from the current GORM docs in the Getting Started section, which I think is importnt to a newcomer

**Comment by graemerocher** [comment]
As mentioned in http://gorm.grails.org/6.0.x/hibernate/manual/index.html#outsideGrails you need to declare the necessary dependencies. The dependencies that are not in the example you have that are mentioned as being necessary in the docs are the connection pool to use:

```groovy
runtime "org.apache.tomcat:tomcat-jdbc:8.5.0"
runtime "org.apache.tomcat.embed:tomcat-embed-logging-log4j:8.5.0"
```

The connection pool can be commons-dbcp, tomcat pool or hikari. If you don't specify a connection pool then a `org.springframework.jdbc.datasource.DriverManagerDataSource` is used, which creates a new connection to the database each time you request a connect.

The problem with this when you use an in-memory database is that h2 is creating a new in-memory database each time a connection is requested. So the tables that were created previously are lost. If you were using a normal database (mysql, postgres or h2 file based database) your example would work fine. 

It is the combination of `DriverManagerDataSource`, which creates and initialises a brand new in-memory database each time a connection is requested (because it is not a pool), and h2 in-memory that causes the issue you are seeing. 

That is why we include a connection pool in the list of necessary dependencies, since people are likely to stumble into this (as you have) and also any real production application would use a pool.

**Comment by ysb33r** [comment]
RIght. I'm going to create a PR which describes this a bit better in the docs.

**Comment by ysb33r** [comment]
On that note of docs isn't the use of `implements GormEntity<Person>` redundant? I thought `@Entity` effectively does that.

**Comment by graemerocher** [comment]
It is, but some IDEs use the fact that the class is in `grails-app/domain` to enable code completion. So by being explicit about implementing the trait you are more likely to obtain completions etc.
